version: '3'

services:
  liquibase:
    image: liquibase/liquibase:4.16
    container_name: liquibase
    ports:
      - 5000:5000
    volumes: 
      - './liquibase/changelog:/liquibase/changelog'
    command: --defaults-file=/liquibase/changelog/liquibase.docker.properties update
