--liquibase formatted sql
--changeset DavidCuy:1 labels:create-database-tables context: First-run-for-liquibase
--comment: Crea las tablas de la base de datos para el sistema P2P

use p2p-solution-db;

CREATE TYPE p2p_schema.p2p_tx_status AS ENUM ('created', 'running', 'done', 'failure')

CREATE TABLE p2p_schema.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  unique_id TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE p2p_schema.p2p_transaction  (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  source_id BIGINT,
  dest_id BIGINT,
  amount FLOAT,
  status p2p_tx_status DEFAULT 'created',
  created_at TIMESTAMP DEFAULT NOW(),

);


--rollback DROP TABLE p2p_schema.p2p_transaction;
--rollback DROP TABLE p2p_schema.users;
--rollback DROP TYPE p2p_schema.p2p_tx_status;